version: '3.8'

services:
  medical-register:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
