server:
  port: 8080

spring:
  config:
    import: optional:env[.env]
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liRas4sqvGZsvdCu
            client-secret: fd65c40d20c1eec4cddcc2522a8ccff713b6992a
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  datasource:
    url: jdbc:h2:mem:medicaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: dmac
    password: pass
  jpa:
    hibernate:
      ddl-auto: update # or use create-drop for dev-only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      add-mappings: false
      static-locations: classpath:/META-INF/resources/

# Optional: logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


joinfaces:
  faces:
    project-stage: Development
  primefaces:
    theme: saga
  jsf:
    servlet:
      init-parameters:
        javax.faces.DEFAULT_SUFFIX: .xhtml
